# Generated by Django 4.0.4 on 2022-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveBigIntegerField(unique=True)),
                ('price_usd', models.PositiveIntegerField()),
                ('price_rub', models.FloatField()),
                ('delivery_time', models.DateField()),
            ],
            options={
                'verbose_name': 'Google Sheet',
                'verbose_name_plural': 'Google Sheets',
            },
        ),
    ]
